---
# ### group_vars/DC1.yml

# custom_structured_configuration_aaa_authentication:
#   policies:
#     local:
#       allow_nopassword: true

# # local users
# local_users:
#   # Username with no password configured
#   - name: arista
#     privilege: 15
#     role: network-admin
#     no_password: true

#   # Username with a password
#   - name: admin
#     privilege: 15
#     role: network-admin
#     sha512_password: "$6$eucN5ngreuExDgwS$xnD7T8jO..GBDX0DUlp.hn.W7yW94xTjSanqgaQGBzPIhDAsyAl9N4oScHvOMvf07uVBFI4mKMxwdVEUVKgY/."

# # OOB Management network default gateway
# mgmt_gateway: 10.10.10.1
# mgmt_interface: Management1

# # dns servers.
# name_servers:
#   - 10.10.10.1

# # NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
# ntp_settings:
#   server_vrf: use_mgmt_interface_vrf
#   servers:
#     - name: 10.10.10.1
#     - name: pool.ntp.org

# # Establish exec/enable role when logging in to switch
# custom_structured_configuration_aaa_authorization:
#   exec:
#     default: local
# Validation lab
# local users
local_users:
    - name: admin
      privilege: 15
      role: network-admin
      sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

    - name: cvpadmin
      privilege: 15
      role: network-admin
      sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

    - name: ansible
      privilege: 15
      role: network-admin
      sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

# Cloud Vision server information
cvp_instance_ips: 
- 10.1.1.10
# cvp_ingestauth_key: ''
# cvp_ingestauth_key: telarista

# OOB Management network default gateway.
mgmt_interface: Management1
mgmt_interface_vrf: MGMT
mgmt_gateway: 10.10.10.1

# dns servers.
name_servers:
  - 10.10.10.1

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
custom_structured_configuration_ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.fr.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.fr.pool.ntp.org
    vrf: MGMT