---
### group_vars/DC1_FABRIC.yml

# Set the Fabric Name - must match an Ansible Inventory Group
fabric_name: DC1_FABRIC

# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: admin
ansible_password: admin
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# Spine Switches (L2 only)
l2spine:
  defaults:
    platform: vEOS-LAB
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    mlag_peer_ipv4_pool: 192.168.100.0/24
    mlag_interfaces: [Ethernet7, Ethernet8]
  node_groups:
    - group: SPINES
      nodes:
        - name: SPINE1
          id: 1
          mgmt_ip: 10.10.10.101/24
        - name: SPINE2
          id: 2
          mgmt_ip: 10.10.10.102/24

# Leaf Switches
l2leaf:
  defaults:
    platform: vEOS-LAB
    mlag_peer_ipv4_pool: 192.168.200.0/24
    uplink_switches: [SPINE1, SPINE2]
    uplink_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet7, Ethernet8]
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384

  node_groups:
    - group: RACK1
      mlag: true
      filter:
        tags: [bluezone, greenzone]
      nodes:
        - name: LEAF1
          id: 1
          mgmt_ip: 10.10.10.111/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        - name: LEAF2
          id: 2
          mgmt_ip: 10.10.10.112/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    - group: RACK2
      mlag: true
      filter:
        tags: [bluezone, orangezone]
      nodes:
        - name: LEAF3
          id: 3
          mgmt_ip: 10.10.10.113/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: LEAF4
          id: 4
          mgmt_ip: 10.10.10.114/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]

#### Override for vEOS/cEOS Lab Caveats ####
p2p_uplinks_mtu: 1500

# Documentation
eos_designs_documentation:
  connected_endpoints: true
